export const COMMODITIES = {
	organics: { value: 500, name: "Organics", tier: 0 },
	ore: { value: 1500, name: "Ore", tier: 0.2 },
	rare_ore: { value: 2000, name: "Transplutonic Ore", tier: 0.3 },
	food: { value: 1000, name: "Food", tier: 1 },
	metals: { value: 3000, name: "Metals", tier: 1.1 },
	rare_metals: { value: 6000, name: "Transplutonics", tier: 1.2 },
	volatiles: { value: 5000, name: "Volatiles", tier: 1.2 },
	fuel: { value: 750, name: "Fuel", tier: 2 },
	supplies: { value: 250, name: "Supplies", tier: 2.1 },
	heavy_machinery: { value: 500, name: "Heavy Machinery", tier: 2.2 },
	domestic_goods: { value: 300, name: "Domestic Goods", tier: 2.3 },
	organs: { value: 2000, name: "Harvested Organs", tier: 2.4 },
	drugs: { value: 1500, name: "Recreational Drugs", tier: 2.5 },
	hand_weapons: { value: 500, name: "Heavy Armaments", tier: 2.6 },
	luxury_goods: { value: 500, name: "Luxury Goods", tier: 2.7 },
	lobster: { name: "Volturnian Lobster", tier: 2.8 },
	crew: { name: "Crew", tier: 3.1 },
	marines: { name: "Marines", tier: 3.4 },
	ships: { value: 300, name: "Ship Hulls & Weapons", tier: 4 },
}
